### ISSUE TITLE
Investigate the build failure with newer conda-build stuff

### ISSUE THREAD

**Issue by jankatins** [conda-forge/inkscape-feedstock#4]
```

(C:\portabel\miniconda\envs\_build) C:\portabel\miniconda\conda-bld\work>if errorlevel 1 exit 1

compiling .pyc files...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\portabel\miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\portabel\miniconda\lib\site-packages\conda_build\main_build.py", line 151, in main
    args_func(args, p)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\main_build.py", line 412, in args_func
    args.func(args, p)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\main_build.py", line 355, in execute

    debug=args.debug)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\build.py", line 650, in build
    preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "C:\portabel\miniconda\lib\site-packages\conda_build\post.py", line 194, in post_process
    compile_missing_pyc(files)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\post.py", line 189, in compile_missing_pyc
    call([python_exe, '-Wi', '-m', 'py_compile', f], cwd=cwd)
  File "C:\portabel\miniconda\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\portabel\miniconda\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\portabel\miniconda\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] the system can't find the file
```

Adding python to the build dependencies raises a lot of errors because the included python files are py2 only :-(

It succeeds nevertheless but then breaks with 

```
Traceback (most recent call last):
  File "C:\portabel\miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\portabel\miniconda\lib\site-packages\conda_build\main_build.py", line 151, in main
    args_func(args, p)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\main_build.py", line 412, in args_func
    args.func(args, p)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\main_build.py", line 355, in execute

    debug=args.debug)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\build.py", line 650, in build
    preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "C:\portabel\miniconda\lib\site-packages\conda_build\post.py", line 194, in post_process
    compile_missing_pyc(files)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\post.py", line 190, in compile_missing_pyc
    coerce_pycache_to_old_style(compile_files, cwd=cwd)
  File "C:\portabel\miniconda\lib\site-packages\conda_build\post.py", line 166, in coerce_pycache_to_old_style
    os.rename(fname, f + 'c')
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\portabel\\miniconda\\envs\\_build\\Library\\inkscape\\python\\Lib\\__pycache__\\_abcoll.cpython-35.pyc' -> 'C:\\portabel\\miniconda\\envs\\_build\\Library\\inkscape\\python\\Lib\\_abcoll.pyc'
```

**Comment by jankatins** [comment]
CC @msarahan because it looks like a new feature in conda-build which breaks this :-(

**Comment by msarahan** [comment]
Can you tell me anything about why those pyc files already exist?

**Comment by jankatins** [comment]
Because inkscape comes with a full python environment which seems to be precompiled (it's a static download which is just repackaged -> https://inkscape.org/en/gallery/item/3938/Inkscape-0.91-1-win64.7z)

**Comment by msarahan** [comment]
I see. I'll see about checking for that condition.

**Comment by jankatins** [comment]
I think here are two problems:
- that conda-build tries to precompile stuff even if no python was added as a build dependency
- that conda-build tries to precompile / move stuff which doesn't belong to the env python (but a new one installed further down in the env)

The first is IMO a problem which needs to be fixed in conda-build. 

The second is more interesting... IMO it should only python compile / move stuff in `Lib` but not in `Library`.
